### ISSUE TITLE
error: invalid path

### ISSUE THREAD

**Issue by cjinchi** [Soulike/Gardenia#67]
- 平台
Windows 10, PowerShell

- 仓库
https://git.soulike.tech:8080/repository/AnalysisAndTesting/papers

- 命令
 git clone https://git.soulike.tech:8080/AnalysisAndTesting/papers.git

- 报错信息

> Cloning into 'papers'...
remote: 枚举对象: 79, 完成.
remote: 对象计数中: 100% (79/79), 完成.
remote: 压缩对象中: 100% (79/79), 完成.
remote: 总共 79（差异 14），复用 0（差异 0），包复用 0iB/s
Unpacking objects: 100% (79/79), 126.76 MiB | 369.00 KiB/s, done.
error: invalid path 'Big Code != Big Vocabulary:Open-Vocabulary Models for Source Code.pdf'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

- 其他
试了2次，均会报错

**Comment by Soulike** [comment]
收到，正在调查原因。

**Comment by Soulike** [comment]
初步判断应当是 Big Code != Big Vocabulary:Open-Vocabulary Models for Source Code 这篇论文的文件名里存在英文冒号，而 Windows 不允许文件名存在英文冒号所以导致 checkout 报错。我已经联系助教了，应当很快就可以修复。
